/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGameContractDuel,
  IGameContractDuelInterface,
} from "../../../contracts/WagerArena.sol/IGameContractDuel";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent1",
        type: "address",
      },
      {
        internalType: "address",
        name: "agent2",
        type: "address",
      },
    ],
    name: "executeDuel",
    outputs: [
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "rounds",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGameContractDuel__factory {
  static readonly abi = _abi;
  static createInterface(): IGameContractDuelInterface {
    return new Interface(_abi) as IGameContractDuelInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGameContractDuel {
    return new Contract(address, _abi, runner) as unknown as IGameContractDuel;
  }
}
