/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAgentController__factory } from "./IAgentController__factory";
export { IGameContractDuel__factory } from "./IGameContractDuel__factory";
export { IPredictionMarket__factory } from "./IPredictionMarket__factory";
export { WagerArena__factory } from "./WagerArena__factory";
