/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPredictionMarket,
  IPredictionMarketInterface,
} from "../../../contracts/WagerArena.sol/IPredictionMarket";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "agent1",
        type: "address",
      },
      {
        internalType: "address",
        name: "agent2",
        type: "address",
      },
    ],
    name: "openPrediction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
    ],
    name: "settlePrediction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPredictionMarket__factory {
  static readonly abi = _abi;
  static createInterface(): IPredictionMarketInterface {
    return new Interface(_abi) as IPredictionMarketInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPredictionMarket {
    return new Contract(address, _abi, runner) as unknown as IPredictionMarket;
  }
}
