/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ShipNFT {
  export type ShipDataStruct = {
    tokenId: BigNumberish;
    battlePower: BigNumberish;
    yieldRate: BigNumberish;
    lastYieldClaim: BigNumberish;
    totalYieldGenerated: BigNumberish;
    mintedAt: BigNumberish;
    shipClass: string;
    isStaked: boolean;
  };

  export type ShipDataStructOutput = [
    tokenId: bigint,
    battlePower: bigint,
    yieldRate: bigint,
    lastYieldClaim: bigint,
    totalYieldGenerated: bigint,
    mintedAt: bigint,
    shipClass: string,
    isStaked: boolean
  ] & {
    tokenId: bigint;
    battlePower: bigint;
    yieldRate: bigint;
    lastYieldClaim: bigint;
    totalYieldGenerated: bigint;
    mintedAt: bigint;
    shipClass: string;
    isStaked: boolean;
  };
}

export interface ShipNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_YIELD_RATE"
      | "BRIGANTINE_THRESHOLD"
      | "FRIGATE_THRESHOLD"
      | "MAN_OF_WAR_THRESHOLD"
      | "MAX_YIELD_RATE"
      | "MIN_BATTLE_POWER"
      | "SECONDS_PER_DAY"
      | "SLOOP_THRESHOLD"
      | "YIELD_MULTIPLIER"
      | "approve"
      | "armadaToken"
      | "balanceOf"
      | "claimMultipleYields"
      | "claimYield"
      | "gameContract"
      | "getApproved"
      | "getClaimableYield"
      | "getContractStats"
      | "getShipAPY"
      | "getShipClassDistribution"
      | "getShipData"
      | "getShipsByOwner"
      | "getTotalClaimableYield"
      | "isApprovedForAll"
      | "mintShipNFT"
      | "name"
      | "nextTokenId"
      | "owner"
      | "ownerOf"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setGameContract"
      | "ships"
      | "stakeShip"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "totalShipsMinted"
      | "transferFrom"
      | "transferOwnership"
      | "unstakeShip"
      | "updateShipPower"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "OwnershipTransferred"
      | "ShipMinted"
      | "ShipPowerUpdated"
      | "ShipStaked"
      | "Transfer"
      | "YieldClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_YIELD_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BRIGANTINE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FRIGATE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAN_OF_WAR_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_YIELD_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BATTLE_POWER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_DAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLOOP_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "YIELD_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "armadaToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMultipleYields",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getShipAPY",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShipClassDistribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getShipData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShipsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalClaimableYield",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintShipNFT",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "ships", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stakeShip",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalShipsMinted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeShip",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateShipPower",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_YIELD_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BRIGANTINE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FRIGATE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAN_OF_WAR_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_YIELD_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BATTLE_POWER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_DAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLOOP_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "YIELD_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "armadaToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimMultipleYields",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimYield", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getShipAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getShipClassDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShipData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShipsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalClaimableYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintShipNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ships", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeShip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalShipsMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeShip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateShipPower",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipMintedEvent {
  export type InputTuple = [
    owner: AddressLike,
    tokenId: BigNumberish,
    battlePower: BigNumberish,
    shipClass: string
  ];
  export type OutputTuple = [
    owner: string,
    tokenId: bigint,
    battlePower: bigint,
    shipClass: string
  ];
  export interface OutputObject {
    owner: string;
    tokenId: bigint;
    battlePower: bigint;
    shipClass: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipPowerUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    oldPower: BigNumberish,
    newPower: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    oldPower: bigint,
    newPower: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    oldPower: bigint;
    newPower: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipStakedEvent {
  export type InputTuple = [tokenId: BigNumberish, staked: boolean];
  export type OutputTuple = [tokenId: bigint, staked: boolean];
  export interface OutputObject {
    tokenId: bigint;
    staked: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldClaimedEvent {
  export type InputTuple = [
    owner: AddressLike,
    tokenId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [owner: string, tokenId: bigint, amount: bigint];
  export interface OutputObject {
    owner: string;
    tokenId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShipNFT extends BaseContract {
  connect(runner?: ContractRunner | null): ShipNFT;
  waitForDeployment(): Promise<this>;

  interface: ShipNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_YIELD_RATE: TypedContractMethod<[], [bigint], "view">;

  BRIGANTINE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  FRIGATE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAN_OF_WAR_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_YIELD_RATE: TypedContractMethod<[], [bigint], "view">;

  MIN_BATTLE_POWER: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_DAY: TypedContractMethod<[], [bigint], "view">;

  SLOOP_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  YIELD_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  armadaToken: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  claimMultipleYields: TypedContractMethod<
    [_tokenIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  claimYield: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameContract: TypedContractMethod<[], [string], "view">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getClaimableYield: TypedContractMethod<
    [_tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getContractStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalMinted: bigint;
        currentSupply: bigint;
        totalYieldGenerated: bigint;
      }
    ],
    "view"
  >;

  getShipAPY: TypedContractMethod<[_tokenId: BigNumberish], [bigint], "view">;

  getShipClassDistribution: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        sloops: bigint;
        brigantines: bigint;
        frigates: bigint;
        manOfWars: bigint;
      }
    ],
    "view"
  >;

  getShipData: TypedContractMethod<
    [_tokenId: BigNumberish],
    [ShipNFT.ShipDataStructOutput],
    "view"
  >;

  getShipsByOwner: TypedContractMethod<
    [_owner: AddressLike],
    [bigint[]],
    "view"
  >;

  getTotalClaimableYield: TypedContractMethod<
    [_owner: AddressLike],
    [bigint],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mintShipNFT: TypedContractMethod<
    [_owner: AddressLike, _battlePower: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nextTokenId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setGameContract: TypedContractMethod<
    [_gameContract: AddressLike],
    [void],
    "nonpayable"
  >;

  ships: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, string, boolean] & {
        tokenId: bigint;
        battlePower: bigint;
        yieldRate: bigint;
        lastYieldClaim: bigint;
        totalYieldGenerated: bigint;
        mintedAt: bigint;
        shipClass: string;
        isStaked: boolean;
      }
    ],
    "view"
  >;

  stakeShip: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalShipsMinted: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstakeShip: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateShipPower: TypedContractMethod<
    [_tokenId: BigNumberish, _newBattlePower: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_YIELD_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BRIGANTINE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FRIGATE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAN_OF_WAR_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_YIELD_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BATTLE_POWER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLOOP_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "YIELD_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "armadaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimMultipleYields"
  ): TypedContractMethod<[_tokenIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimYield"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gameContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getClaimableYield"
  ): TypedContractMethod<[_tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalMinted: bigint;
        currentSupply: bigint;
        totalYieldGenerated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShipAPY"
  ): TypedContractMethod<[_tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getShipClassDistribution"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        sloops: bigint;
        brigantines: bigint;
        frigates: bigint;
        manOfWars: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShipData"
  ): TypedContractMethod<
    [_tokenId: BigNumberish],
    [ShipNFT.ShipDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShipsByOwner"
  ): TypedContractMethod<[_owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTotalClaimableYield"
  ): TypedContractMethod<[_owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintShipNFT"
  ): TypedContractMethod<
    [_owner: AddressLike, _battlePower: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGameContract"
  ): TypedContractMethod<[_gameContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ships"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, string, boolean] & {
        tokenId: bigint;
        battlePower: bigint;
        yieldRate: bigint;
        lastYieldClaim: bigint;
        totalYieldGenerated: bigint;
        mintedAt: bigint;
        shipClass: string;
        isStaked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakeShip"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalShipsMinted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeShip"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateShipPower"
  ): TypedContractMethod<
    [_tokenId: BigNumberish, _newBattlePower: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ShipMinted"
  ): TypedContractEvent<
    ShipMintedEvent.InputTuple,
    ShipMintedEvent.OutputTuple,
    ShipMintedEvent.OutputObject
  >;
  getEvent(
    key: "ShipPowerUpdated"
  ): TypedContractEvent<
    ShipPowerUpdatedEvent.InputTuple,
    ShipPowerUpdatedEvent.OutputTuple,
    ShipPowerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ShipStaked"
  ): TypedContractEvent<
    ShipStakedEvent.InputTuple,
    ShipStakedEvent.OutputTuple,
    ShipStakedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "YieldClaimed"
  ): TypedContractEvent<
    YieldClaimedEvent.InputTuple,
    YieldClaimedEvent.OutputTuple,
    YieldClaimedEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ShipMinted(address,uint256,uint256,string)": TypedContractEvent<
      ShipMintedEvent.InputTuple,
      ShipMintedEvent.OutputTuple,
      ShipMintedEvent.OutputObject
    >;
    ShipMinted: TypedContractEvent<
      ShipMintedEvent.InputTuple,
      ShipMintedEvent.OutputTuple,
      ShipMintedEvent.OutputObject
    >;

    "ShipPowerUpdated(uint256,uint256,uint256)": TypedContractEvent<
      ShipPowerUpdatedEvent.InputTuple,
      ShipPowerUpdatedEvent.OutputTuple,
      ShipPowerUpdatedEvent.OutputObject
    >;
    ShipPowerUpdated: TypedContractEvent<
      ShipPowerUpdatedEvent.InputTuple,
      ShipPowerUpdatedEvent.OutputTuple,
      ShipPowerUpdatedEvent.OutputObject
    >;

    "ShipStaked(uint256,bool)": TypedContractEvent<
      ShipStakedEvent.InputTuple,
      ShipStakedEvent.OutputTuple,
      ShipStakedEvent.OutputObject
    >;
    ShipStaked: TypedContractEvent<
      ShipStakedEvent.InputTuple,
      ShipStakedEvent.OutputTuple,
      ShipStakedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "YieldClaimed(address,uint256,uint256)": TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
    YieldClaimed: TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
  };
}
