/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IArmadaGuild } from "./IArmadaGuild";
export type { IArmadaToken } from "./IArmadaToken";
export type { IBattlePass } from "./IBattlePass";
export type { IShipNFT } from "./IShipNFT";
export type { MantleArmada } from "./MantleArmada";
