/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "AgentController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentController__factory>;
    getContractFactory(
      name: "IGameContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGameContract__factory>;
    getContractFactory(
      name: "ArmadaGuild",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArmadaGuild__factory>;
    getContractFactory(
      name: "ArmadaToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArmadaToken__factory>;
    getContractFactory(
      name: "BattlePass",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BattlePass__factory>;
    getContractFactory(
      name: "IArmadaToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IArmadaToken__factory>;
    getContractFactory(
      name: "IArmadaGuild",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IArmadaGuild__factory>;
    getContractFactory(
      name: "IArmadaToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IArmadaToken__factory>;
    getContractFactory(
      name: "IBattlePass",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBattlePass__factory>;
    getContractFactory(
      name: "IShipNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IShipNFT__factory>;
    getContractFactory(
      name: "MantleArmada",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MantleArmada__factory>;
    getContractFactory(
      name: "PredictionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PredictionMarket__factory>;
    getContractFactory(
      name: "SEASToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SEASToken__factory>;
    getContractFactory(
      name: "IArmadaToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IArmadaToken__factory>;
    getContractFactory(
      name: "ShipNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShipNFT__factory>;
    getContractFactory(
      name: "IAgentControllerTournament",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentControllerTournament__factory>;
    getContractFactory(
      name: "IGameContractTournament",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGameContractTournament__factory>;
    getContractFactory(
      name: "TournamentArena",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TournamentArena__factory>;
    getContractFactory(
      name: "IAgentController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentController__factory>;
    getContractFactory(
      name: "IGameContractDuel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGameContractDuel__factory>;
    getContractFactory(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPredictionMarket__factory>;
    getContractFactory(
      name: "WagerArena",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WagerArena__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "AgentController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentController>;
    getContractAt(
      name: "IGameContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGameContract>;
    getContractAt(
      name: "ArmadaGuild",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArmadaGuild>;
    getContractAt(
      name: "ArmadaToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArmadaToken>;
    getContractAt(
      name: "BattlePass",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BattlePass>;
    getContractAt(
      name: "IArmadaToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IArmadaToken>;
    getContractAt(
      name: "IArmadaGuild",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IArmadaGuild>;
    getContractAt(
      name: "IArmadaToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IArmadaToken>;
    getContractAt(
      name: "IBattlePass",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBattlePass>;
    getContractAt(
      name: "IShipNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IShipNFT>;
    getContractAt(
      name: "MantleArmada",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MantleArmada>;
    getContractAt(
      name: "PredictionMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PredictionMarket>;
    getContractAt(
      name: "SEASToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SEASToken>;
    getContractAt(
      name: "IArmadaToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IArmadaToken>;
    getContractAt(
      name: "ShipNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ShipNFT>;
    getContractAt(
      name: "IAgentControllerTournament",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentControllerTournament>;
    getContractAt(
      name: "IGameContractTournament",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGameContractTournament>;
    getContractAt(
      name: "TournamentArena",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TournamentArena>;
    getContractAt(
      name: "IAgentController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentController>;
    getContractAt(
      name: "IGameContractDuel",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGameContractDuel>;
    getContractAt(
      name: "IPredictionMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPredictionMarket>;
    getContractAt(
      name: "WagerArena",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WagerArena>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "AgentController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentController>;
    deployContract(
      name: "IGameContract",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGameContract>;
    deployContract(
      name: "ArmadaGuild",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArmadaGuild>;
    deployContract(
      name: "ArmadaToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArmadaToken>;
    deployContract(
      name: "BattlePass",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BattlePass>;
    deployContract(
      name: "IArmadaToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArmadaToken>;
    deployContract(
      name: "IArmadaGuild",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArmadaGuild>;
    deployContract(
      name: "IArmadaToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArmadaToken>;
    deployContract(
      name: "IBattlePass",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBattlePass>;
    deployContract(
      name: "IShipNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IShipNFT>;
    deployContract(
      name: "MantleArmada",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MantleArmada>;
    deployContract(
      name: "PredictionMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarket>;
    deployContract(
      name: "SEASToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SEASToken>;
    deployContract(
      name: "IArmadaToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArmadaToken>;
    deployContract(
      name: "ShipNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShipNFT>;
    deployContract(
      name: "IAgentControllerTournament",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentControllerTournament>;
    deployContract(
      name: "IGameContractTournament",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGameContractTournament>;
    deployContract(
      name: "TournamentArena",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TournamentArena>;
    deployContract(
      name: "IAgentController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentController>;
    deployContract(
      name: "IGameContractDuel",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGameContractDuel>;
    deployContract(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "WagerArena",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WagerArena>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "AgentController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentController>;
    deployContract(
      name: "IGameContract",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGameContract>;
    deployContract(
      name: "ArmadaGuild",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArmadaGuild>;
    deployContract(
      name: "ArmadaToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArmadaToken>;
    deployContract(
      name: "BattlePass",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BattlePass>;
    deployContract(
      name: "IArmadaToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArmadaToken>;
    deployContract(
      name: "IArmadaGuild",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArmadaGuild>;
    deployContract(
      name: "IArmadaToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArmadaToken>;
    deployContract(
      name: "IBattlePass",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBattlePass>;
    deployContract(
      name: "IShipNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IShipNFT>;
    deployContract(
      name: "MantleArmada",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MantleArmada>;
    deployContract(
      name: "PredictionMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarket>;
    deployContract(
      name: "SEASToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SEASToken>;
    deployContract(
      name: "IArmadaToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArmadaToken>;
    deployContract(
      name: "ShipNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShipNFT>;
    deployContract(
      name: "IAgentControllerTournament",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentControllerTournament>;
    deployContract(
      name: "IGameContractTournament",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGameContractTournament>;
    deployContract(
      name: "TournamentArena",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TournamentArena>;
    deployContract(
      name: "IAgentController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentController>;
    deployContract(
      name: "IGameContractDuel",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGameContractDuel>;
    deployContract(
      name: "IPredictionMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "WagerArena",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WagerArena>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
