/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAgentControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "getAgentStats"
      | "isRegistered"
      | "updateAfterMatch"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getAgentStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAfterMatch",
    values: [AddressLike, boolean, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAfterMatch",
    data: BytesLike
  ): Result;
}

export interface IAgentController extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentController;
  waitForDeployment(): Promise<this>;

  interface: IAgentControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        owner: string;
        agentType: bigint;
        eloRating: bigint;
        wins: bigint;
        losses: bigint;
        bankroll: bigint;
        totalWagers: bigint;
        isActive: boolean;
        agentAlias: string;
      }
    ],
    "view"
  >;

  getAgentStats: TypedContractMethod<
    [agentAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        bankroll: bigint;
        wins: bigint;
        losses: bigint;
        eloRating: bigint;
        totalWagers: bigint;
      }
    ],
    "view"
  >;

  isRegistered: TypedContractMethod<
    [agentAddress: AddressLike],
    [boolean],
    "view"
  >;

  updateAfterMatch: TypedContractMethod<
    [agentAddress: AddressLike, won: boolean, wagerAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        owner: string;
        agentType: bigint;
        eloRating: bigint;
        wins: bigint;
        losses: bigint;
        bankroll: bigint;
        totalWagers: bigint;
        isActive: boolean;
        agentAlias: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentStats"
  ): TypedContractMethod<
    [agentAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        bankroll: bigint;
        wins: bigint;
        losses: bigint;
        eloRating: bigint;
        totalWagers: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[agentAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateAfterMatch"
  ): TypedContractMethod<
    [agentAddress: AddressLike, won: boolean, wagerAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
