/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgentController } from "./IAgentController";
export type { IGameContractDuel } from "./IGameContractDuel";
export type { IPredictionMarket } from "./IPredictionMarket";
export type { WagerArena } from "./WagerArena";
