/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface WagerArenaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "HOUSE_FEE_BPS"
      | "MATCH_EXPIRY"
      | "MAX_WAGER"
      | "MIN_WAGER"
      | "acceptMatch"
      | "agentController"
      | "agentMatches"
      | "cancelMatch"
      | "createMatch"
      | "executeBattle"
      | "gameContract"
      | "getAgentMatchHistory"
      | "getMatchDetails"
      | "getOpenMatches"
      | "getRecentMatches"
      | "matchCounter"
      | "matches"
      | "owner"
      | "predictionMarket"
      | "renounceOwnership"
      | "seasToken"
      | "setPredictionMarket"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchAccepted"
      | "MatchCancelled"
      | "MatchCompleted"
      | "MatchCreated"
      | "OwnershipTransferred"
      | "TreasurySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "HOUSE_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MATCH_EXPIRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_WAGER", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_WAGER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentMatches",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBattle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentMatchHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenMatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentMatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictionMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "seasToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setPredictionMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "HOUSE_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MATCH_EXPIRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_WAGER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_WAGER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBattle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentMatchHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictionMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seasToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPredictionMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace MatchAcceptedEvent {
  export type InputTuple = [matchId: BigNumberish, opponent: AddressLike];
  export type OutputTuple = [matchId: bigint, opponent: string];
  export interface OutputObject {
    matchId: bigint;
    opponent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCancelledEvent {
  export type InputTuple = [matchId: BigNumberish, challenger: AddressLike];
  export type OutputTuple = [matchId: bigint, challenger: string];
  export interface OutputObject {
    matchId: bigint;
    challenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCompletedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    winner: AddressLike,
    payout: BigNumberish,
    rounds: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    winner: string,
    payout: bigint,
    rounds: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
    payout: bigint;
    rounds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    challenger: AddressLike,
    opponent: AddressLike,
    wagerAmount: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    challenger: string,
    opponent: string,
    wagerAmount: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    challenger: string;
    opponent: string;
    wagerAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySetEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WagerArena extends BaseContract {
  connect(runner?: ContractRunner | null): WagerArena;
  waitForDeployment(): Promise<this>;

  interface: WagerArenaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  HOUSE_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MATCH_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  MAX_WAGER: TypedContractMethod<[], [bigint], "view">;

  MIN_WAGER: TypedContractMethod<[], [bigint], "view">;

  acceptMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  agentController: TypedContractMethod<[], [string], "view">;

  agentMatches: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  cancelMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMatch: TypedContractMethod<
    [wagerAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  executeBattle: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameContract: TypedContractMethod<[], [string], "view">;

  getAgentMatchHistory: TypedContractMethod<
    [agent: AddressLike],
    [bigint[]],
    "view"
  >;

  getMatchDetails: TypedContractMethod<
    [matchId: BigNumberish],
    [
      [string, string, bigint, boolean, boolean, string, bigint] & {
        agent1: string;
        agent2: string;
        wagerAmount: bigint;
        isAccepted: boolean;
        isCompleted: boolean;
        winner: string;
        rounds: bigint;
      }
    ],
    "view"
  >;

  getOpenMatches: TypedContractMethod<[], [bigint[]], "view">;

  getRecentMatches: TypedContractMethod<
    [count: BigNumberish],
    [bigint[]],
    "view"
  >;

  matchCounter: TypedContractMethod<[], [bigint], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        string,
        bigint,
        bigint
      ] & {
        matchId: bigint;
        agent1: string;
        agent2: string;
        wagerAmount: bigint;
        isAccepted: boolean;
        isCompleted: boolean;
        isCancelled: boolean;
        winner: string;
        timestamp: bigint;
        rounds: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  predictionMarket: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seasToken: TypedContractMethod<[], [string], "view">;

  setPredictionMarket: TypedContractMethod<
    [_pm: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "HOUSE_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MATCH_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_WAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agentController"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentMatches"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<[wagerAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "executeBattle"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gameContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentMatchHistory"
  ): TypedContractMethod<[agent: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMatchDetails"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [
      [string, string, bigint, boolean, boolean, string, bigint] & {
        agent1: string;
        agent2: string;
        wagerAmount: bigint;
        isAccepted: boolean;
        isCompleted: boolean;
        winner: string;
        rounds: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOpenMatches"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRecentMatches"
  ): TypedContractMethod<[count: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "matchCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        string,
        bigint,
        bigint
      ] & {
        matchId: bigint;
        agent1: string;
        agent2: string;
        wagerAmount: bigint;
        isAccepted: boolean;
        isCompleted: boolean;
        isCancelled: boolean;
        winner: string;
        timestamp: bigint;
        rounds: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predictionMarket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seasToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPredictionMarket"
  ): TypedContractMethod<[_pm: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MatchAccepted"
  ): TypedContractEvent<
    MatchAcceptedEvent.InputTuple,
    MatchAcceptedEvent.OutputTuple,
    MatchAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "MatchCancelled"
  ): TypedContractEvent<
    MatchCancelledEvent.InputTuple,
    MatchCancelledEvent.OutputTuple,
    MatchCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MatchCompleted"
  ): TypedContractEvent<
    MatchCompletedEvent.InputTuple,
    MatchCompletedEvent.OutputTuple,
    MatchCompletedEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySet"
  ): TypedContractEvent<
    TreasurySetEvent.InputTuple,
    TreasurySetEvent.OutputTuple,
    TreasurySetEvent.OutputObject
  >;

  filters: {
    "MatchAccepted(uint256,address)": TypedContractEvent<
      MatchAcceptedEvent.InputTuple,
      MatchAcceptedEvent.OutputTuple,
      MatchAcceptedEvent.OutputObject
    >;
    MatchAccepted: TypedContractEvent<
      MatchAcceptedEvent.InputTuple,
      MatchAcceptedEvent.OutputTuple,
      MatchAcceptedEvent.OutputObject
    >;

    "MatchCancelled(uint256,address)": TypedContractEvent<
      MatchCancelledEvent.InputTuple,
      MatchCancelledEvent.OutputTuple,
      MatchCancelledEvent.OutputObject
    >;
    MatchCancelled: TypedContractEvent<
      MatchCancelledEvent.InputTuple,
      MatchCancelledEvent.OutputTuple,
      MatchCancelledEvent.OutputObject
    >;

    "MatchCompleted(uint256,address,uint256,uint256)": TypedContractEvent<
      MatchCompletedEvent.InputTuple,
      MatchCompletedEvent.OutputTuple,
      MatchCompletedEvent.OutputObject
    >;
    MatchCompleted: TypedContractEvent<
      MatchCompletedEvent.InputTuple,
      MatchCompletedEvent.OutputTuple,
      MatchCompletedEvent.OutputObject
    >;

    "MatchCreated(uint256,address,address,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TreasurySet(address)": TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
    TreasurySet: TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
  };
}
