/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ArmadaGuild {
  export type GuildStruct = {
    name: string;
    leader: AddressLike;
    createdAt: BigNumberish;
    memberCount: BigNumberish;
    treasury: BigNumberish;
    isActive: boolean;
    totalBattlesWon: BigNumberish;
    logo: string;
    level: BigNumberish;
  };

  export type GuildStructOutput = [
    name: string,
    leader: string,
    createdAt: bigint,
    memberCount: bigint,
    treasury: bigint,
    isActive: boolean,
    totalBattlesWon: bigint,
    logo: string,
    level: bigint
  ] & {
    name: string;
    leader: string;
    createdAt: bigint;
    memberCount: bigint;
    treasury: bigint;
    isActive: boolean;
    totalBattlesWon: bigint;
    logo: string;
    level: bigint;
  };

  export type GuildMemberStruct = {
    memberAddress: AddressLike;
    joinedAt: BigNumberish;
    contribution: BigNumberish;
    isOfficer: boolean;
    lastDividendClaim: BigNumberish;
  };

  export type GuildMemberStructOutput = [
    memberAddress: string,
    joinedAt: bigint,
    contribution: bigint,
    isOfficer: boolean,
    lastDividendClaim: bigint
  ] & {
    memberAddress: string;
    joinedAt: bigint;
    contribution: bigint;
    isOfficer: boolean;
    lastDividendClaim: bigint;
  };

  export type GuildWarStruct = {
    warId: BigNumberish;
    guild1: BigNumberish;
    guild2: BigNumberish;
    score1: BigNumberish;
    score2: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    completed: boolean;
    winner: AddressLike;
  };

  export type GuildWarStructOutput = [
    warId: bigint,
    guild1: bigint,
    guild2: bigint,
    score1: bigint,
    score2: bigint,
    startTime: bigint,
    endTime: bigint,
    completed: boolean,
    winner: string
  ] & {
    warId: bigint;
    guild1: bigint;
    guild2: bigint;
    score1: bigint;
    score2: bigint;
    startTime: bigint;
    endTime: bigint;
    completed: boolean;
    winner: string;
  };
}

export interface ArmadaGuildInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GUILD_CREATION_COST"
      | "GUILD_WAR_DURATION"
      | "MIN_MEMBERS_FOR_WAR"
      | "TREASURY_FEE_PERCENT"
      | "addTreasuryReward"
      | "claimGuildDividends"
      | "createGuild"
      | "endGuildWar"
      | "gameContract"
      | "getClaimableDividends"
      | "getGuild"
      | "getGuildMembers"
      | "getGuildWar"
      | "getMemberContribution"
      | "getPlayerGuild"
      | "getTopGuilds"
      | "guildMembers"
      | "guildWars"
      | "guilds"
      | "joinGuild"
      | "leaveGuild"
      | "memberContribution"
      | "nextGuildId"
      | "nextWarId"
      | "owner"
      | "playerToGuild"
      | "promoteToOfficer"
      | "renounceOwnership"
      | "setGameContract"
      | "startGuildWar"
      | "transferLeadership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DividendsClaimed"
      | "GuildCreated"
      | "GuildLevelUp"
      | "GuildWarEnded"
      | "GuildWarStarted"
      | "LeadershipTransferred"
      | "MemberJoined"
      | "MemberLeft"
      | "OwnershipTransferred"
      | "TreasuryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "GUILD_CREATION_COST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUILD_WAR_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_MEMBERS_FOR_WAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addTreasuryReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimGuildDividends",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createGuild",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "endGuildWar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableDividends",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuild",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuildMembers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuildWar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberContribution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerGuild",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopGuilds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guildMembers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guildWars",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guilds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGuild",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "leaveGuild",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "memberContribution",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextGuildId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nextWarId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerToGuild",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "promoteToOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGameContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startGuildWar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferLeadership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "GUILD_CREATION_COST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUILD_WAR_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_MEMBERS_FOR_WAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTreasuryReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimGuildDividends",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createGuild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endGuildWar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableDividends",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGuild", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGuildMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuildWar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerGuild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopGuilds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guildMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guildWars", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "guilds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGuild", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leaveGuild", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "memberContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextGuildId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextWarId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerToGuild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "promoteToOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startGuildWar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferLeadership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DividendsClaimedEvent {
  export type InputTuple = [
    guildId: BigNumberish,
    member: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [guildId: bigint, member: string, amount: bigint];
  export interface OutputObject {
    guildId: bigint;
    member: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuildCreatedEvent {
  export type InputTuple = [
    guildId: BigNumberish,
    name: string,
    leader: AddressLike
  ];
  export type OutputTuple = [guildId: bigint, name: string, leader: string];
  export interface OutputObject {
    guildId: bigint;
    name: string;
    leader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuildLevelUpEvent {
  export type InputTuple = [guildId: BigNumberish, newLevel: BigNumberish];
  export type OutputTuple = [guildId: bigint, newLevel: bigint];
  export interface OutputObject {
    guildId: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuildWarEndedEvent {
  export type InputTuple = [warId: BigNumberish, winnerGuild: BigNumberish];
  export type OutputTuple = [warId: bigint, winnerGuild: bigint];
  export interface OutputObject {
    warId: bigint;
    winnerGuild: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuildWarStartedEvent {
  export type InputTuple = [
    warId: BigNumberish,
    guild1: BigNumberish,
    guild2: BigNumberish
  ];
  export type OutputTuple = [warId: bigint, guild1: bigint, guild2: bigint];
  export interface OutputObject {
    warId: bigint;
    guild1: bigint;
    guild2: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeadershipTransferredEvent {
  export type InputTuple = [
    guildId: BigNumberish,
    oldLeader: AddressLike,
    newLeader: AddressLike
  ];
  export type OutputTuple = [
    guildId: bigint,
    oldLeader: string,
    newLeader: string
  ];
  export interface OutputObject {
    guildId: bigint;
    oldLeader: string;
    newLeader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberJoinedEvent {
  export type InputTuple = [guildId: BigNumberish, member: AddressLike];
  export type OutputTuple = [guildId: bigint, member: string];
  export interface OutputObject {
    guildId: bigint;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberLeftEvent {
  export type InputTuple = [guildId: BigNumberish, member: AddressLike];
  export type OutputTuple = [guildId: bigint, member: string];
  export interface OutputObject {
    guildId: bigint;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [
    guildId: BigNumberish,
    amount: BigNumberish,
    contributor: AddressLike
  ];
  export type OutputTuple = [
    guildId: bigint,
    amount: bigint,
    contributor: string
  ];
  export interface OutputObject {
    guildId: bigint;
    amount: bigint;
    contributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArmadaGuild extends BaseContract {
  connect(runner?: ContractRunner | null): ArmadaGuild;
  waitForDeployment(): Promise<this>;

  interface: ArmadaGuildInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GUILD_CREATION_COST: TypedContractMethod<[], [bigint], "view">;

  GUILD_WAR_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_MEMBERS_FOR_WAR: TypedContractMethod<[], [bigint], "view">;

  TREASURY_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  addTreasuryReward: TypedContractMethod<
    [_memberAddress: AddressLike, _goldAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimGuildDividends: TypedContractMethod<[], [void], "nonpayable">;

  createGuild: TypedContractMethod<
    [_name: string, _logo: string],
    [void],
    "nonpayable"
  >;

  endGuildWar: TypedContractMethod<
    [_warId: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameContract: TypedContractMethod<[], [string], "view">;

  getClaimableDividends: TypedContractMethod<
    [_member: AddressLike],
    [bigint],
    "view"
  >;

  getGuild: TypedContractMethod<
    [_guildId: BigNumberish],
    [ArmadaGuild.GuildStructOutput],
    "view"
  >;

  getGuildMembers: TypedContractMethod<
    [_guildId: BigNumberish],
    [ArmadaGuild.GuildMemberStructOutput[]],
    "view"
  >;

  getGuildWar: TypedContractMethod<
    [_warId: BigNumberish],
    [ArmadaGuild.GuildWarStructOutput],
    "view"
  >;

  getMemberContribution: TypedContractMethod<
    [_member: AddressLike],
    [bigint],
    "view"
  >;

  getPlayerGuild: TypedContractMethod<[_player: AddressLike], [bigint], "view">;

  getTopGuilds: TypedContractMethod<
    [_count: BigNumberish],
    [[bigint[], bigint[]]],
    "view"
  >;

  guildMembers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint] & {
        memberAddress: string;
        joinedAt: bigint;
        contribution: bigint;
        isOfficer: boolean;
        lastDividendClaim: bigint;
      }
    ],
    "view"
  >;

  guildWars: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        warId: bigint;
        guild1: bigint;
        guild2: bigint;
        score1: bigint;
        score2: bigint;
        startTime: bigint;
        endTime: bigint;
        completed: boolean;
        winner: string;
      }
    ],
    "view"
  >;

  guilds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        bigint
      ] & {
        name: string;
        leader: string;
        createdAt: bigint;
        memberCount: bigint;
        treasury: bigint;
        isActive: boolean;
        totalBattlesWon: bigint;
        logo: string;
        level: bigint;
      }
    ],
    "view"
  >;

  joinGuild: TypedContractMethod<
    [_guildId: BigNumberish],
    [void],
    "nonpayable"
  >;

  leaveGuild: TypedContractMethod<[], [void], "nonpayable">;

  memberContribution: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  nextGuildId: TypedContractMethod<[], [bigint], "view">;

  nextWarId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  playerToGuild: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  promoteToOfficer: TypedContractMethod<
    [_member: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGameContract: TypedContractMethod<
    [_gameContract: AddressLike],
    [void],
    "nonpayable"
  >;

  startGuildWar: TypedContractMethod<
    [_guild2: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferLeadership: TypedContractMethod<
    [_newLeader: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GUILD_CREATION_COST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GUILD_WAR_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_MEMBERS_FOR_WAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addTreasuryReward"
  ): TypedContractMethod<
    [_memberAddress: AddressLike, _goldAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimGuildDividends"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createGuild"
  ): TypedContractMethod<[_name: string, _logo: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "endGuildWar"
  ): TypedContractMethod<[_warId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gameContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getClaimableDividends"
  ): TypedContractMethod<[_member: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGuild"
  ): TypedContractMethod<
    [_guildId: BigNumberish],
    [ArmadaGuild.GuildStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGuildMembers"
  ): TypedContractMethod<
    [_guildId: BigNumberish],
    [ArmadaGuild.GuildMemberStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGuildWar"
  ): TypedContractMethod<
    [_warId: BigNumberish],
    [ArmadaGuild.GuildWarStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMemberContribution"
  ): TypedContractMethod<[_member: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerGuild"
  ): TypedContractMethod<[_player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTopGuilds"
  ): TypedContractMethod<
    [_count: BigNumberish],
    [[bigint[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "guildMembers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint] & {
        memberAddress: string;
        joinedAt: bigint;
        contribution: bigint;
        isOfficer: boolean;
        lastDividendClaim: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "guildWars"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        warId: bigint;
        guild1: bigint;
        guild2: bigint;
        score1: bigint;
        score2: bigint;
        startTime: bigint;
        endTime: bigint;
        completed: boolean;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "guilds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        bigint
      ] & {
        name: string;
        leader: string;
        createdAt: bigint;
        memberCount: bigint;
        treasury: bigint;
        isActive: boolean;
        totalBattlesWon: bigint;
        logo: string;
        level: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGuild"
  ): TypedContractMethod<[_guildId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "leaveGuild"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "memberContribution"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextGuildId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextWarId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerToGuild"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "promoteToOfficer"
  ): TypedContractMethod<[_member: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGameContract"
  ): TypedContractMethod<[_gameContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startGuildWar"
  ): TypedContractMethod<[_guild2: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferLeadership"
  ): TypedContractMethod<[_newLeader: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DividendsClaimed"
  ): TypedContractEvent<
    DividendsClaimedEvent.InputTuple,
    DividendsClaimedEvent.OutputTuple,
    DividendsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "GuildCreated"
  ): TypedContractEvent<
    GuildCreatedEvent.InputTuple,
    GuildCreatedEvent.OutputTuple,
    GuildCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GuildLevelUp"
  ): TypedContractEvent<
    GuildLevelUpEvent.InputTuple,
    GuildLevelUpEvent.OutputTuple,
    GuildLevelUpEvent.OutputObject
  >;
  getEvent(
    key: "GuildWarEnded"
  ): TypedContractEvent<
    GuildWarEndedEvent.InputTuple,
    GuildWarEndedEvent.OutputTuple,
    GuildWarEndedEvent.OutputObject
  >;
  getEvent(
    key: "GuildWarStarted"
  ): TypedContractEvent<
    GuildWarStartedEvent.InputTuple,
    GuildWarStartedEvent.OutputTuple,
    GuildWarStartedEvent.OutputObject
  >;
  getEvent(
    key: "LeadershipTransferred"
  ): TypedContractEvent<
    LeadershipTransferredEvent.InputTuple,
    LeadershipTransferredEvent.OutputTuple,
    LeadershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "MemberJoined"
  ): TypedContractEvent<
    MemberJoinedEvent.InputTuple,
    MemberJoinedEvent.OutputTuple,
    MemberJoinedEvent.OutputObject
  >;
  getEvent(
    key: "MemberLeft"
  ): TypedContractEvent<
    MemberLeftEvent.InputTuple,
    MemberLeftEvent.OutputTuple,
    MemberLeftEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;

  filters: {
    "DividendsClaimed(uint256,address,uint256)": TypedContractEvent<
      DividendsClaimedEvent.InputTuple,
      DividendsClaimedEvent.OutputTuple,
      DividendsClaimedEvent.OutputObject
    >;
    DividendsClaimed: TypedContractEvent<
      DividendsClaimedEvent.InputTuple,
      DividendsClaimedEvent.OutputTuple,
      DividendsClaimedEvent.OutputObject
    >;

    "GuildCreated(uint256,string,address)": TypedContractEvent<
      GuildCreatedEvent.InputTuple,
      GuildCreatedEvent.OutputTuple,
      GuildCreatedEvent.OutputObject
    >;
    GuildCreated: TypedContractEvent<
      GuildCreatedEvent.InputTuple,
      GuildCreatedEvent.OutputTuple,
      GuildCreatedEvent.OutputObject
    >;

    "GuildLevelUp(uint256,uint256)": TypedContractEvent<
      GuildLevelUpEvent.InputTuple,
      GuildLevelUpEvent.OutputTuple,
      GuildLevelUpEvent.OutputObject
    >;
    GuildLevelUp: TypedContractEvent<
      GuildLevelUpEvent.InputTuple,
      GuildLevelUpEvent.OutputTuple,
      GuildLevelUpEvent.OutputObject
    >;

    "GuildWarEnded(uint256,uint256)": TypedContractEvent<
      GuildWarEndedEvent.InputTuple,
      GuildWarEndedEvent.OutputTuple,
      GuildWarEndedEvent.OutputObject
    >;
    GuildWarEnded: TypedContractEvent<
      GuildWarEndedEvent.InputTuple,
      GuildWarEndedEvent.OutputTuple,
      GuildWarEndedEvent.OutputObject
    >;

    "GuildWarStarted(uint256,uint256,uint256)": TypedContractEvent<
      GuildWarStartedEvent.InputTuple,
      GuildWarStartedEvent.OutputTuple,
      GuildWarStartedEvent.OutputObject
    >;
    GuildWarStarted: TypedContractEvent<
      GuildWarStartedEvent.InputTuple,
      GuildWarStartedEvent.OutputTuple,
      GuildWarStartedEvent.OutputObject
    >;

    "LeadershipTransferred(uint256,address,address)": TypedContractEvent<
      LeadershipTransferredEvent.InputTuple,
      LeadershipTransferredEvent.OutputTuple,
      LeadershipTransferredEvent.OutputObject
    >;
    LeadershipTransferred: TypedContractEvent<
      LeadershipTransferredEvent.InputTuple,
      LeadershipTransferredEvent.OutputTuple,
      LeadershipTransferredEvent.OutputObject
    >;

    "MemberJoined(uint256,address)": TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;
    MemberJoined: TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;

    "MemberLeft(uint256,address)": TypedContractEvent<
      MemberLeftEvent.InputTuple,
      MemberLeftEvent.OutputTuple,
      MemberLeftEvent.OutputObject
    >;
    MemberLeft: TypedContractEvent<
      MemberLeftEvent.InputTuple,
      MemberLeftEvent.OutputTuple,
      MemberLeftEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TreasuryUpdated(uint256,uint256,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
  };
}
