/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as battlePassSol from "./BattlePass.sol";
export type { battlePassSol };
import type * as mantleArmadaSol from "./MantleArmada.sol";
export type { mantleArmadaSol };
import type * as shipNftSol from "./ShipNFT.sol";
export type { shipNftSol };
export type { ArmadaGuild } from "./ArmadaGuild";
export type { ArmadaToken } from "./ArmadaToken";
