/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGameContract,
  IGameContractInterface,
} from "../../../contracts/AgentController.sol/IGameContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "boatName",
        type: "string",
      },
      {
        internalType: "bool",
        name: "isPirate",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "startLocation",
        type: "uint256",
      },
    ],
    name: "createAccount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "getShipStats",
    outputs: [
      {
        internalType: "uint256",
        name: "attack",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "defense",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "hp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxHp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gold",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "crew",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "location",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isPirate",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGameContract__factory {
  static readonly abi = _abi;
  static createInterface(): IGameContractInterface {
    return new Interface(_abi) as IGameContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGameContract {
    return new Contract(address, _abi, runner) as unknown as IGameContract;
  }
}
