/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentController__factory } from "./AgentController__factory";
export { IGameContract__factory } from "./IGameContract__factory";
