/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace BattlePass {
  export type PassLevelStruct = {
    experienceRequired: BigNumberish;
    goldReward: BigNumberish;
    diamondReward: BigNumberish;
    armadaReward: BigNumberish;
    cosmeticReward: string;
    hasPremiumReward: boolean;
  };

  export type PassLevelStructOutput = [
    experienceRequired: bigint,
    goldReward: bigint,
    diamondReward: bigint,
    armadaReward: bigint,
    cosmeticReward: string,
    hasPremiumReward: boolean
  ] & {
    experienceRequired: bigint;
    goldReward: bigint;
    diamondReward: bigint;
    armadaReward: bigint;
    cosmeticReward: string;
    hasPremiumReward: boolean;
  };

  export type PlayerPassStruct = {
    season: BigNumberish;
    level: BigNumberish;
    experience: BigNumberish;
    isPremium: boolean;
    lastRewardClaimed: BigNumberish;
    createdAt: BigNumberish;
  };

  export type PlayerPassStructOutput = [
    season: bigint,
    level: bigint,
    experience: bigint,
    isPremium: boolean,
    lastRewardClaimed: bigint,
    createdAt: bigint
  ] & {
    season: bigint;
    level: bigint;
    experience: bigint;
    isPremium: boolean;
    lastRewardClaimed: bigint;
    createdAt: bigint;
  };
}

export interface BattlePassInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_LEVEL"
      | "PREMIUM_COST"
      | "SEASON_DURATION"
      | "XP_PER_BATTLE_WIN"
      | "XP_PER_CHECKIN"
      | "XP_PER_GPM_CLAIM"
      | "XP_PER_UPGRADE"
      | "armadaToken"
      | "claimLevelReward"
      | "claimMultipleLevelRewards"
      | "createPass"
      | "currentSeason"
      | "endSeasonAndStartNew"
      | "gainExperience"
      | "gameContract"
      | "getPassLevel"
      | "getPlayerPass"
      | "getSeasonInfo"
      | "getUnclaimedRewards"
      | "getXPForNextLevel"
      | "hasActivePass"
      | "owner"
      | "passLevels"
      | "playerPasses"
      | "renounceOwnership"
      | "seasonEndTime"
      | "seasonStartTime"
      | "setGameContract"
      | "transferOwnership"
      | "upgradeToPremium"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExperienceGained"
      | "LevelUp"
      | "OwnershipTransferred"
      | "PassCreated"
      | "PassUpgradedToPremium"
      | "RewardClaimed"
      | "SeasonEnded"
      | "SeasonStarted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MAX_LEVEL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PREMIUM_COST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SEASON_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XP_PER_BATTLE_WIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XP_PER_CHECKIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XP_PER_GPM_CLAIM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XP_PER_UPGRADE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "armadaToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimLevelReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMultipleLevelRewards",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createPass",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentSeason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "endSeasonAndStartNew",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gainExperience",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "gameContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPassLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerPass",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSeasonInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnclaimedRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getXPForNextLevel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActivePass",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "passLevels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerPasses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seasonEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seasonStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGameContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToPremium",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MAX_LEVEL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PREMIUM_COST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SEASON_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "XP_PER_BATTLE_WIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "XP_PER_CHECKIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "XP_PER_GPM_CLAIM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "XP_PER_UPGRADE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "armadaToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimLevelReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimMultipleLevelRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPass", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentSeason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endSeasonAndStartNew",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gainExperience",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPassLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerPass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSeasonInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnclaimedRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getXPForNextLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActivePass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "passLevels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerPasses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seasonEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seasonStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToPremium",
    data: BytesLike
  ): Result;
}

export namespace ExperienceGainedEvent {
  export type InputTuple = [
    player: AddressLike,
    xp: BigNumberish,
    action: string
  ];
  export type OutputTuple = [player: string, xp: bigint, action: string];
  export interface OutputObject {
    player: string;
    xp: bigint;
    action: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LevelUpEvent {
  export type InputTuple = [player: AddressLike, newLevel: BigNumberish];
  export type OutputTuple = [player: string, newLevel: bigint];
  export interface OutputObject {
    player: string;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PassCreatedEvent {
  export type InputTuple = [
    player: AddressLike,
    isPremium: boolean,
    season: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    isPremium: boolean,
    season: bigint
  ];
  export interface OutputObject {
    player: string;
    isPremium: boolean;
    season: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PassUpgradedToPremiumEvent {
  export type InputTuple = [player: AddressLike, season: BigNumberish];
  export type OutputTuple = [player: string, season: bigint];
  export interface OutputObject {
    player: string;
    season: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    player: AddressLike,
    level: BigNumberish,
    goldReward: BigNumberish,
    diamondReward: BigNumberish,
    armadaReward: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    level: bigint,
    goldReward: bigint,
    diamondReward: bigint,
    armadaReward: bigint
  ];
  export interface OutputObject {
    player: string;
    level: bigint;
    goldReward: bigint;
    diamondReward: bigint;
    armadaReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeasonEndedEvent {
  export type InputTuple = [season: BigNumberish];
  export type OutputTuple = [season: bigint];
  export interface OutputObject {
    season: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeasonStartedEvent {
  export type InputTuple = [
    season: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    season: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    season: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BattlePass extends BaseContract {
  connect(runner?: ContractRunner | null): BattlePass;
  waitForDeployment(): Promise<this>;

  interface: BattlePassInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_LEVEL: TypedContractMethod<[], [bigint], "view">;

  PREMIUM_COST: TypedContractMethod<[], [bigint], "view">;

  SEASON_DURATION: TypedContractMethod<[], [bigint], "view">;

  XP_PER_BATTLE_WIN: TypedContractMethod<[], [bigint], "view">;

  XP_PER_CHECKIN: TypedContractMethod<[], [bigint], "view">;

  XP_PER_GPM_CLAIM: TypedContractMethod<[], [bigint], "view">;

  XP_PER_UPGRADE: TypedContractMethod<[], [bigint], "view">;

  armadaToken: TypedContractMethod<[], [string], "view">;

  claimLevelReward: TypedContractMethod<
    [_level: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimMultipleLevelRewards: TypedContractMethod<
    [_levels: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  createPass: TypedContractMethod<[], [void], "nonpayable">;

  currentSeason: TypedContractMethod<[], [bigint], "view">;

  endSeasonAndStartNew: TypedContractMethod<[], [void], "nonpayable">;

  gainExperience: TypedContractMethod<
    [_player: AddressLike, _xp: BigNumberish, _action: string],
    [void],
    "nonpayable"
  >;

  gameContract: TypedContractMethod<[], [string], "view">;

  getPassLevel: TypedContractMethod<
    [_level: BigNumberish],
    [BattlePass.PassLevelStructOutput],
    "view"
  >;

  getPlayerPass: TypedContractMethod<
    [_player: AddressLike],
    [BattlePass.PlayerPassStructOutput],
    "view"
  >;

  getSeasonInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        season: bigint;
        startTime: bigint;
        endTime: bigint;
        timeRemaining: bigint;
      }
    ],
    "view"
  >;

  getUnclaimedRewards: TypedContractMethod<
    [_player: AddressLike],
    [
      [bigint[], bigint, bigint, bigint] & {
        levels: bigint[];
        totalGold: bigint;
        totalDiamonds: bigint;
        totalArmada: bigint;
      }
    ],
    "view"
  >;

  getXPForNextLevel: TypedContractMethod<
    [_player: AddressLike],
    [bigint],
    "view"
  >;

  hasActivePass: TypedContractMethod<[_player: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  passLevels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, boolean] & {
        experienceRequired: bigint;
        goldReward: bigint;
        diamondReward: bigint;
        armadaReward: bigint;
        cosmeticReward: string;
        hasPremiumReward: boolean;
      }
    ],
    "view"
  >;

  playerPasses: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint] & {
        season: bigint;
        level: bigint;
        experience: bigint;
        isPremium: boolean;
        lastRewardClaimed: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seasonEndTime: TypedContractMethod<[], [bigint], "view">;

  seasonStartTime: TypedContractMethod<[], [bigint], "view">;

  setGameContract: TypedContractMethod<
    [_gameContract: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToPremium: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_LEVEL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PREMIUM_COST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SEASON_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "XP_PER_BATTLE_WIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "XP_PER_CHECKIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "XP_PER_GPM_CLAIM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "XP_PER_UPGRADE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "armadaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimLevelReward"
  ): TypedContractMethod<[_level: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimMultipleLevelRewards"
  ): TypedContractMethod<[_levels: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPass"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentSeason"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "endSeasonAndStartNew"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gainExperience"
  ): TypedContractMethod<
    [_player: AddressLike, _xp: BigNumberish, _action: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gameContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPassLevel"
  ): TypedContractMethod<
    [_level: BigNumberish],
    [BattlePass.PassLevelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerPass"
  ): TypedContractMethod<
    [_player: AddressLike],
    [BattlePass.PlayerPassStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSeasonInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        season: bigint;
        startTime: bigint;
        endTime: bigint;
        timeRemaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUnclaimedRewards"
  ): TypedContractMethod<
    [_player: AddressLike],
    [
      [bigint[], bigint, bigint, bigint] & {
        levels: bigint[];
        totalGold: bigint;
        totalDiamonds: bigint;
        totalArmada: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getXPForNextLevel"
  ): TypedContractMethod<[_player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasActivePass"
  ): TypedContractMethod<[_player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "passLevels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, boolean] & {
        experienceRequired: bigint;
        goldReward: bigint;
        diamondReward: bigint;
        armadaReward: bigint;
        cosmeticReward: string;
        hasPremiumReward: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerPasses"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint] & {
        season: bigint;
        level: bigint;
        experience: bigint;
        isPremium: boolean;
        lastRewardClaimed: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seasonEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "seasonStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setGameContract"
  ): TypedContractMethod<[_gameContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToPremium"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ExperienceGained"
  ): TypedContractEvent<
    ExperienceGainedEvent.InputTuple,
    ExperienceGainedEvent.OutputTuple,
    ExperienceGainedEvent.OutputObject
  >;
  getEvent(
    key: "LevelUp"
  ): TypedContractEvent<
    LevelUpEvent.InputTuple,
    LevelUpEvent.OutputTuple,
    LevelUpEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PassCreated"
  ): TypedContractEvent<
    PassCreatedEvent.InputTuple,
    PassCreatedEvent.OutputTuple,
    PassCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PassUpgradedToPremium"
  ): TypedContractEvent<
    PassUpgradedToPremiumEvent.InputTuple,
    PassUpgradedToPremiumEvent.OutputTuple,
    PassUpgradedToPremiumEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SeasonEnded"
  ): TypedContractEvent<
    SeasonEndedEvent.InputTuple,
    SeasonEndedEvent.OutputTuple,
    SeasonEndedEvent.OutputObject
  >;
  getEvent(
    key: "SeasonStarted"
  ): TypedContractEvent<
    SeasonStartedEvent.InputTuple,
    SeasonStartedEvent.OutputTuple,
    SeasonStartedEvent.OutputObject
  >;

  filters: {
    "ExperienceGained(address,uint256,string)": TypedContractEvent<
      ExperienceGainedEvent.InputTuple,
      ExperienceGainedEvent.OutputTuple,
      ExperienceGainedEvent.OutputObject
    >;
    ExperienceGained: TypedContractEvent<
      ExperienceGainedEvent.InputTuple,
      ExperienceGainedEvent.OutputTuple,
      ExperienceGainedEvent.OutputObject
    >;

    "LevelUp(address,uint256)": TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;
    LevelUp: TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PassCreated(address,bool,uint256)": TypedContractEvent<
      PassCreatedEvent.InputTuple,
      PassCreatedEvent.OutputTuple,
      PassCreatedEvent.OutputObject
    >;
    PassCreated: TypedContractEvent<
      PassCreatedEvent.InputTuple,
      PassCreatedEvent.OutputTuple,
      PassCreatedEvent.OutputObject
    >;

    "PassUpgradedToPremium(address,uint256)": TypedContractEvent<
      PassUpgradedToPremiumEvent.InputTuple,
      PassUpgradedToPremiumEvent.OutputTuple,
      PassUpgradedToPremiumEvent.OutputObject
    >;
    PassUpgradedToPremium: TypedContractEvent<
      PassUpgradedToPremiumEvent.InputTuple,
      PassUpgradedToPremiumEvent.OutputTuple,
      PassUpgradedToPremiumEvent.OutputObject
    >;

    "RewardClaimed(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "SeasonEnded(uint256)": TypedContractEvent<
      SeasonEndedEvent.InputTuple,
      SeasonEndedEvent.OutputTuple,
      SeasonEndedEvent.OutputObject
    >;
    SeasonEnded: TypedContractEvent<
      SeasonEndedEvent.InputTuple,
      SeasonEndedEvent.OutputTuple,
      SeasonEndedEvent.OutputObject
    >;

    "SeasonStarted(uint256,uint256,uint256)": TypedContractEvent<
      SeasonStartedEvent.InputTuple,
      SeasonStartedEvent.OutputTuple,
      SeasonStartedEvent.OutputObject
    >;
    SeasonStarted: TypedContractEvent<
      SeasonStartedEvent.InputTuple,
      SeasonStartedEvent.OutputTuple,
      SeasonStartedEvent.OutputObject
    >;
  };
}
