/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agentControllerSol from "./AgentController.sol";
export type { agentControllerSol };
import type * as battlePassSol from "./BattlePass.sol";
export type { battlePassSol };
import type * as mantleArmadaSol from "./MantleArmada.sol";
export type { mantleArmadaSol };
import type * as shipNftSol from "./ShipNFT.sol";
export type { shipNftSol };
import type * as tournamentArenaSol from "./TournamentArena.sol";
export type { tournamentArenaSol };
import type * as wagerArenaSol from "./WagerArena.sol";
export type { wagerArenaSol };
export type { ArmadaGuild } from "./ArmadaGuild";
export type { ArmadaToken } from "./ArmadaToken";
export type { PredictionMarket } from "./PredictionMarket";
export type { SEASToken } from "./SEASToken";
