/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_BET"
      | "PROTOCOL_FEE_BPS"
      | "bets"
      | "claimWinnings"
      | "getActivePredictions"
      | "getBet"
      | "getPrediction"
      | "getPredictionByMatch"
      | "matchToPrediction"
      | "openPrediction"
      | "owner"
      | "placeBet"
      | "predictionCounter"
      | "predictions"
      | "renounceOwnership"
      | "seasToken"
      | "setWagerArena"
      | "settlePrediction"
      | "transferOwnership"
      | "treasury"
      | "wagerArena"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "OwnershipTransferred"
      | "PredictionOpened"
      | "PredictionSettled"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MIN_BET", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bets",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActivePredictions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBet",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrediction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPredictionByMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchToPrediction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openPrediction",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "predictions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "seasToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setWagerArena",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlePrediction",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wagerArena",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MIN_BET", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActivePredictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPredictionByMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchToPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seasToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWagerArena",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlePrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wagerArena", data: BytesLike): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    predictionId: BigNumberish,
    bettor: AddressLike,
    betOnAgent1: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    predictionId: bigint,
    bettor: string,
    betOnAgent1: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    predictionId: bigint;
    bettor: string;
    betOnAgent1: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionOpenedEvent {
  export type InputTuple = [
    predictionId: BigNumberish,
    matchId: BigNumberish,
    agent1: AddressLike,
    agent2: AddressLike
  ];
  export type OutputTuple = [
    predictionId: bigint,
    matchId: bigint,
    agent1: string,
    agent2: string
  ];
  export interface OutputObject {
    predictionId: bigint;
    matchId: bigint;
    agent1: string;
    agent2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionSettledEvent {
  export type InputTuple = [predictionId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [predictionId: bigint, winner: string];
  export interface OutputObject {
    predictionId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    predictionId: BigNumberish,
    claimer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    predictionId: bigint,
    claimer: string,
    amount: bigint
  ];
  export interface OutputObject {
    predictionId: bigint;
    claimer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_BET: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  bets: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, boolean, boolean] & {
        amount: bigint;
        betOnAgent1: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;

  claimWinnings: TypedContractMethod<
    [predictionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActivePredictions: TypedContractMethod<
    [count: BigNumberish],
    [bigint[]],
    "view"
  >;

  getBet: TypedContractMethod<
    [predictionId: BigNumberish, bettor: AddressLike],
    [
      [bigint, boolean, boolean] & {
        amount: bigint;
        betOnAgent1: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getPrediction: TypedContractMethod<
    [predictionId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean, string] & {
        matchId: bigint;
        agent1: string;
        agent2: string;
        agent1Pool: bigint;
        agent2Pool: bigint;
        isOpen: boolean;
        isSettled: boolean;
        winner: string;
      }
    ],
    "view"
  >;

  getPredictionByMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [bigint],
    "view"
  >;

  matchToPrediction: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  openPrediction: TypedContractMethod<
    [matchId: BigNumberish, agent1: AddressLike, agent2: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [predictionId: BigNumberish, betOnAgent1: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  predictionCounter: TypedContractMethod<[], [bigint], "view">;

  predictions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean, string] & {
        matchId: bigint;
        agent1: string;
        agent2: string;
        agent1Pool: bigint;
        agent2Pool: bigint;
        isOpen: boolean;
        isSettled: boolean;
        winner: string;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seasToken: TypedContractMethod<[], [string], "view">;

  setWagerArena: TypedContractMethod<
    [_wagerArena: AddressLike],
    [void],
    "nonpayable"
  >;

  settlePrediction: TypedContractMethod<
    [matchId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  wagerArena: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, boolean, boolean] & {
        amount: bigint;
        betOnAgent1: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[predictionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActivePredictions"
  ): TypedContractMethod<[count: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getBet"
  ): TypedContractMethod<
    [predictionId: BigNumberish, bettor: AddressLike],
    [
      [bigint, boolean, boolean] & {
        amount: bigint;
        betOnAgent1: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrediction"
  ): TypedContractMethod<
    [predictionId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean, string] & {
        matchId: bigint;
        agent1: string;
        agent2: string;
        agent1Pool: bigint;
        agent2Pool: bigint;
        isOpen: boolean;
        isSettled: boolean;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPredictionByMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "matchToPrediction"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "openPrediction"
  ): TypedContractMethod<
    [matchId: BigNumberish, agent1: AddressLike, agent2: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [predictionId: BigNumberish, betOnAgent1: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "predictionCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "predictions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean, string] & {
        matchId: bigint;
        agent1: string;
        agent2: string;
        agent1Pool: bigint;
        agent2Pool: bigint;
        isOpen: boolean;
        isSettled: boolean;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seasToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setWagerArena"
  ): TypedContractMethod<[_wagerArena: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlePrediction"
  ): TypedContractMethod<
    [matchId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wagerArena"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PredictionOpened"
  ): TypedContractEvent<
    PredictionOpenedEvent.InputTuple,
    PredictionOpenedEvent.OutputTuple,
    PredictionOpenedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionSettled"
  ): TypedContractEvent<
    PredictionSettledEvent.InputTuple,
    PredictionSettledEvent.OutputTuple,
    PredictionSettledEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(uint256,address,bool,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PredictionOpened(uint256,uint256,address,address)": TypedContractEvent<
      PredictionOpenedEvent.InputTuple,
      PredictionOpenedEvent.OutputTuple,
      PredictionOpenedEvent.OutputObject
    >;
    PredictionOpened: TypedContractEvent<
      PredictionOpenedEvent.InputTuple,
      PredictionOpenedEvent.OutputTuple,
      PredictionOpenedEvent.OutputObject
    >;

    "PredictionSettled(uint256,address)": TypedContractEvent<
      PredictionSettledEvent.InputTuple,
      PredictionSettledEvent.OutputTuple,
      PredictionSettledEvent.OutputObject
    >;
    PredictionSettled: TypedContractEvent<
      PredictionSettledEvent.InputTuple,
      PredictionSettledEvent.OutputTuple,
      PredictionSettledEvent.OutputObject
    >;

    "WinningsClaimed(uint256,address,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
