/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IArmadaToken,
  IArmadaTokenInterface,
} from "../../../../artifacts/contracts/BattlePass.sol/IArmadaToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "mintFromGameplay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IArmadaToken__factory {
  static readonly abi = _abi;
  static createInterface(): IArmadaTokenInterface {
    return new Interface(_abi) as IArmadaTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IArmadaToken {
    return new Contract(address, _abi, runner) as unknown as IArmadaToken;
  }
}
