/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBattlePass,
  IBattlePassInterface,
} from "../../../../artifacts/contracts/MantleArmada.sol/IBattlePass";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "xp",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "action",
        type: "string",
      },
    ],
    name: "gainExperience",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBattlePass__factory {
  static readonly abi = _abi;
  static createInterface(): IBattlePassInterface {
    return new Interface(_abi) as IBattlePassInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBattlePass {
    return new Contract(address, _abi, runner) as unknown as IBattlePass;
  }
}
