/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IShipNFT,
  IShipNFTInterface,
} from "../../../../artifacts/contracts/MantleArmada.sol/IShipNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "newBattlePower",
        type: "uint256",
      },
    ],
    name: "updateShipPower",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IShipNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IShipNFTInterface {
    return new Interface(_abi) as IShipNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IShipNFT {
    return new Contract(address, _abi, runner) as unknown as IShipNFT;
  }
}
