/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGameContractTournament,
  IGameContractTournamentInterface,
} from "../../../contracts/TournamentArena.sol/IGameContractTournament";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent1",
        type: "address",
      },
      {
        internalType: "address",
        name: "agent2",
        type: "address",
      },
    ],
    name: "executeDuel",
    outputs: [
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "rounds",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "getShipStats",
    outputs: [
      {
        internalType: "uint256",
        name: "attack",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "defense",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "hp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxHp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gold",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "crew",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "location",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isPirate",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGameContractTournament__factory {
  static readonly abi = _abi;
  static createInterface(): IGameContractTournamentInterface {
    return new Interface(_abi) as IGameContractTournamentInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGameContractTournament {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGameContractTournament;
  }
}
