/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AgentControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentList"
      | "agents"
      | "depositBankroll"
      | "gameContract"
      | "getAgentCount"
      | "getAgentDecision"
      | "getAgentStats"
      | "getLeaderboard"
      | "isRegistered"
      | "owner"
      | "registerAgent"
      | "renounceOwnership"
      | "seasToken"
      | "setWagerArena"
      | "transferOwnership"
      | "updateAfterMatch"
      | "wagerArena"
      | "withdrawProfits"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDecision"
      | "AgentRegistered"
      | "BankrollDeposited"
      | "MatchResultRecorded"
      | "OwnershipTransferred"
      | "ProfitsWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "depositBankroll",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentDecision",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "seasToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setWagerArena",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAfterMatch",
    values: [AddressLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wagerArena",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProfits",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositBankroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seasToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWagerArena",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAfterMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wagerArena", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProfits",
    data: BytesLike
  ): Result;
}

export namespace AgentDecisionEvent {
  export type InputTuple = [
    agent: AddressLike,
    action: string,
    value: BigNumberish
  ];
  export type OutputTuple = [agent: string, action: string, value: bigint];
  export interface OutputObject {
    agent: string;
    action: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentAddress: AddressLike,
    agentType: BigNumberish,
    agentAlias: string
  ];
  export type OutputTuple = [
    agentAddress: string,
    agentType: bigint,
    agentAlias: string
  ];
  export interface OutputObject {
    agentAddress: string;
    agentType: bigint;
    agentAlias: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BankrollDepositedEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchResultRecordedEvent {
  export type InputTuple = [
    agent: AddressLike,
    won: boolean,
    eloAfter: BigNumberish
  ];
  export type OutputTuple = [agent: string, won: boolean, eloAfter: bigint];
  export interface OutputObject {
    agent: string;
    won: boolean;
    eloAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitsWithdrawnEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentController extends BaseContract {
  connect(runner?: ContractRunner | null): AgentController;
  waitForDeployment(): Promise<this>;

  interface: AgentControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        owner: string;
        agentType: bigint;
        eloRating: bigint;
        wins: bigint;
        losses: bigint;
        bankroll: bigint;
        totalWagers: bigint;
        isActive: boolean;
        agentAlias: string;
      }
    ],
    "view"
  >;

  depositBankroll: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameContract: TypedContractMethod<[], [string], "view">;

  getAgentCount: TypedContractMethod<[], [bigint], "view">;

  getAgentDecision: TypedContractMethod<
    [agentAddress: AddressLike],
    [[string, bigint] & { action: string; value: bigint }],
    "view"
  >;

  getAgentStats: TypedContractMethod<
    [agentAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        bankroll: bigint;
        wins: bigint;
        losses: bigint;
        eloRating: bigint;
        totalWagers: bigint;
      }
    ],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [count: BigNumberish],
    [[string[], bigint[]] & { addrs: string[]; elos: bigint[] }],
    "view"
  >;

  isRegistered: TypedContractMethod<
    [agentAddress: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [
      agentType: BigNumberish,
      initialBankroll: BigNumberish,
      agentAlias: string
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seasToken: TypedContractMethod<[], [string], "view">;

  setWagerArena: TypedContractMethod<
    [_wagerArena: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAfterMatch: TypedContractMethod<
    [agentAddress: AddressLike, won: boolean, wagerAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  wagerArena: TypedContractMethod<[], [string], "view">;

  withdrawProfits: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        owner: string;
        agentType: bigint;
        eloRating: bigint;
        wins: bigint;
        losses: bigint;
        bankroll: bigint;
        totalWagers: bigint;
        isActive: boolean;
        agentAlias: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositBankroll"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gameContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentDecision"
  ): TypedContractMethod<
    [agentAddress: AddressLike],
    [[string, bigint] & { action: string; value: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentStats"
  ): TypedContractMethod<
    [agentAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        bankroll: bigint;
        wins: bigint;
        losses: bigint;
        eloRating: bigint;
        totalWagers: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [count: BigNumberish],
    [[string[], bigint[]] & { addrs: string[]; elos: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[agentAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      agentType: BigNumberish,
      initialBankroll: BigNumberish,
      agentAlias: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seasToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setWagerArena"
  ): TypedContractMethod<[_wagerArena: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAfterMatch"
  ): TypedContractMethod<
    [agentAddress: AddressLike, won: boolean, wagerAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wagerArena"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawProfits"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AgentDecision"
  ): TypedContractEvent<
    AgentDecisionEvent.InputTuple,
    AgentDecisionEvent.OutputTuple,
    AgentDecisionEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BankrollDeposited"
  ): TypedContractEvent<
    BankrollDepositedEvent.InputTuple,
    BankrollDepositedEvent.OutputTuple,
    BankrollDepositedEvent.OutputObject
  >;
  getEvent(
    key: "MatchResultRecorded"
  ): TypedContractEvent<
    MatchResultRecordedEvent.InputTuple,
    MatchResultRecordedEvent.OutputTuple,
    MatchResultRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProfitsWithdrawn"
  ): TypedContractEvent<
    ProfitsWithdrawnEvent.InputTuple,
    ProfitsWithdrawnEvent.OutputTuple,
    ProfitsWithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentDecision(address,string,uint256)": TypedContractEvent<
      AgentDecisionEvent.InputTuple,
      AgentDecisionEvent.OutputTuple,
      AgentDecisionEvent.OutputObject
    >;
    AgentDecision: TypedContractEvent<
      AgentDecisionEvent.InputTuple,
      AgentDecisionEvent.OutputTuple,
      AgentDecisionEvent.OutputObject
    >;

    "AgentRegistered(address,uint8,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "BankrollDeposited(address,uint256)": TypedContractEvent<
      BankrollDepositedEvent.InputTuple,
      BankrollDepositedEvent.OutputTuple,
      BankrollDepositedEvent.OutputObject
    >;
    BankrollDeposited: TypedContractEvent<
      BankrollDepositedEvent.InputTuple,
      BankrollDepositedEvent.OutputTuple,
      BankrollDepositedEvent.OutputObject
    >;

    "MatchResultRecorded(address,bool,uint256)": TypedContractEvent<
      MatchResultRecordedEvent.InputTuple,
      MatchResultRecordedEvent.OutputTuple,
      MatchResultRecordedEvent.OutputObject
    >;
    MatchResultRecorded: TypedContractEvent<
      MatchResultRecordedEvent.InputTuple,
      MatchResultRecordedEvent.OutputTuple,
      MatchResultRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProfitsWithdrawn(address,uint256)": TypedContractEvent<
      ProfitsWithdrawnEvent.InputTuple,
      ProfitsWithdrawnEvent.OutputTuple,
      ProfitsWithdrawnEvent.OutputObject
    >;
    ProfitsWithdrawn: TypedContractEvent<
      ProfitsWithdrawnEvent.InputTuple,
      ProfitsWithdrawnEvent.OutputTuple,
      ProfitsWithdrawnEvent.OutputObject
    >;
  };
}
