/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IGameContractInterface extends Interface {
  getFunction(
    nameOrSignature: "createAccount" | "getShipStats"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createAccount",
    values: [string, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShipStats",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShipStats",
    data: BytesLike
  ): Result;
}

export interface IGameContract extends BaseContract {
  connect(runner?: ContractRunner | null): IGameContract;
  waitForDeployment(): Promise<this>;

  interface: IGameContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createAccount: TypedContractMethod<
    [boatName: string, isPirate: boolean, startLocation: BigNumberish],
    [void],
    "nonpayable"
  >;

  getShipStats: TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        attack: bigint;
        defense: bigint;
        hp: bigint;
        maxHp: bigint;
        gold: bigint;
        crew: bigint;
        location: bigint;
        isPirate: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createAccount"
  ): TypedContractMethod<
    [boatName: string, isPirate: boolean, startLocation: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getShipStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        attack: bigint;
        defense: bigint;
        hp: bigint;
        maxHp: bigint;
        gold: bigint;
        crew: bigint;
        location: bigint;
        isPirate: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
