/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentController } from "./AgentController";
export type { IGameContract } from "./IGameContract";
